# dev 分支 自动部署到测试机
name: deploy for dev

on:
    push:
        branches:
            - 'master' # 只针对 main 分支
        paths:
            - '.github/workflows/*'
            # - '__test__/**' # dev 不需要立即测试
            - 'src/**'
            - 'Dockerfile'
            - 'docker-compose.yml'
            - 'bin/*'

jobs:
    deploy-dev:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2 #获取最新代码
            - name: set ssh key # 临时设置 ssh key   把私钥放到ubuntu上面
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/authorized_keys  #私钥内容放到id_rsa
                  chmod 600 ~/.ssh/authorized_keys
                  ssh-keyscan "111.229.71.210" >> ~/.ssh/known_hosts
            - name: deploy # 部署test
              run: |
                  ssh root@111.229.71.210 -i 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXEJfuMYU0fWdwlHs+Sagtq2keVF8W18aoeuN601pcNCk9A5opCIYEWyaQyj/J/OE+hQ4g6vyr6ZEdxo4+ALYcyE9OKIirFrWGH5BSwZZNpHgJN8SBOlCdrWXX2+tNwLos8m8Gd0fEUt7SxEazx866MUjIG4wnuJXk0yjuiNHyDYbiTI4OoG4celmvBMt/3rdmbs06m+0/I8RuodY0LCp3hXXm00MAMxS4M1rASKvov9T2jublkixdxGljxxWP2kfrGpghoXbV2zNgRdnXxcruaZqatjRUhbMHeDpwIQ24qvelUtM4yO1Tbk4CF2OpWSdTELq9o10CjOcFvFEbU4malrGPNnO6vH7Ek2PD02quUPYHvH5qvLVkTCMx0H+r8BFTBlLxzQAsMMRqbOr9yCzFYGuyEw0qA2ij86ZwA2b7MScm8w3YdPySdVWQ/+Q0hiAf9ehYtU5ANAP3r4X90ca+6hktaGe6qAj2HCKuqZ1QALfS9N0kUCDwjsqcwfGC0D8= 1461089222@qq.com
                  ' "
                    cd /home/work/imooc-lego/editor-server;
                    git remote add origin https://${{secrets.WFP_TOKEN}}@github.com:haha58/lego-admin.git;
                    git checkout dev;
                    git pull origin dev; # 重新下载最新代码
                    git remote remove origin; # 删除 origin ，否则会暴露 github 密码
                    # 启动 docker
                    docker compose build editor-server; # 和 docker-compose.yml service 名字一致
                    docker compose up -d;
                  "
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa
